import { defineConfig, globalIgnores } from 'eslint/config';
import customConfig from 'eslint-config-phun-ky';

export default defineConfig([
  // Generated by release-it on every release
  globalIgnores(['CHANGELOG.md']),
  {
    extends: [customConfig]
  },
  {
    files: ['**/*.md'],
    rules: {
      'no-irregular-whitespace': 'off',
      '@stylistic/indent': 'off'
    }
  },
  {
    // Placeholders like [e.g. iOS] are meant to be filled in, not links
    files: ['.github/ISSUE_TEMPLATE/**/*.md'],
    rules: {
      'markdown/no-missing-label-refs': 'off'
    }
  }
]);
